name: Hello World

on:
  push:
    branches:
      - master  # Modifier pour correspondre à la branche souhaitée

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Vérifier l'âge
      run: |
        if [ $AGE -ge 18 ]; then
          RESULT="Vous êtes majeur"
        else
          RESULT="Vous êtes mineur" 
      env:
        AGE: 18

    - name: Hello Thibaut
      run: echo "Hello, $NOM , tu es $RESULT"
      env:
        NOM: Thibaut
