name: Hello World

on:
  push:
    branches:
      - master  # Modifier pour correspondre à la branche souhaitée

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Hello World
      run: echo "Hello, World!"
